version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend: 
    build: ./backend/
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend  
    ports:
      - "3000:3000"
    
volumes:
  db_data:
  
